#define LPAREN                          1
#define RPAREN                          2
#define EQ                              3
#define COMMA                           4
#define PLUS                            5
#define MINUS                           6
#define STAR                            7
#define SLASH                           8
#define VERB                            9
#define IDENT                          10
#define NUMERIC                        11
